# Niri global configuration
# Provides Niri setup config and module imports
# Feel free to add, remove and modify anything here

{ variables, pkgs, lib, ... }:
  let
    ide = variables.IDE or "zed";
    browser = variables.browser or "firefox";
    terminal = variables.terminal or "ghostty";
    desktopShell = variables.desktopShell or "";
    noctaliaStartup = lib.optionalString (desktopShell == "noctalia") ''
      spawn-at-startup {
        command "noctalia-shell"
      }
    '';

    # Import keybinds
    keybindsModule = import ./keybinds.nix {
      inherit terminal browser ide;
    };
in {
  home.packages = with pkgs; [
    niri
    grim
    slurp
    wl-clipboard
  ];

  # Generate Niri config.kdl
  xdg.configFile."niri/config.kdl".text = ''
    // Niri config
    // Generated by NixOS configuration

    ${keybindsModule}
    ${noctaliaStartup}
  '';
}